// flow-typed signature: ee790b3b3a301e14a7db55d224908bfe
// flow-typed version: <<STUB>>/@types/jest_v^24.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
