// flow-typed signature: e3f3280845a6e5dd6c0af89d6b633994
// flow-typed version: <<STUB>>/babel-plugin-import_v^1.9.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-import/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-import/lib/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-import/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-import/lib/index'>;
}
declare module 'babel-plugin-import/lib/Plugin.js' {
  declare module.exports: $Exports<'babel-plugin-import/lib/Plugin'>;
}
