// flow-typed signature: 58410a82784faa4de419515a33caddc7
// flow-typed version: <<STUB>>/canner-script_v^1.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-script/lib/configure' {
  declare module.exports: any;
}

declare module 'canner-script/lib/flow-types' {
  declare module.exports: any;
}

declare module 'canner-script/lib/index' {
  declare module.exports: any;
}

declare module 'canner-script/lib/layout' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/array' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/basic' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/boolean' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/date' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/file' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/geoPoint' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/image' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/index' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/mapPoint' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/number' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/object' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/relation' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/root' {
  declare module.exports: any;
}

declare module 'canner-script/lib/models/string' {
  declare module.exports: any;
}

declare module 'canner-script/lib/utils' {
  declare module.exports: any;
}

declare module 'canner-script/lib/validator' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitorManager' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/body' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/fieldset' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/hocs' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/index' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/layer1-2Fieldset' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/layer3Fieldset' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/layerGTE4Fieldset' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/validator' {
  declare module.exports: any;
}

declare module 'canner-script/lib/visitors/variants' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-script/index' {
  declare module.exports: $Exports<'canner-script'>;
}
declare module 'canner-script/index.js' {
  declare module.exports: $Exports<'canner-script'>;
}
declare module 'canner-script/lib/configure.js' {
  declare module.exports: $Exports<'canner-script/lib/configure'>;
}
declare module 'canner-script/lib/flow-types.js' {
  declare module.exports: $Exports<'canner-script/lib/flow-types'>;
}
declare module 'canner-script/lib/index.js' {
  declare module.exports: $Exports<'canner-script/lib/index'>;
}
declare module 'canner-script/lib/layout.js' {
  declare module.exports: $Exports<'canner-script/lib/layout'>;
}
declare module 'canner-script/lib/models/array.js' {
  declare module.exports: $Exports<'canner-script/lib/models/array'>;
}
declare module 'canner-script/lib/models/basic.js' {
  declare module.exports: $Exports<'canner-script/lib/models/basic'>;
}
declare module 'canner-script/lib/models/boolean.js' {
  declare module.exports: $Exports<'canner-script/lib/models/boolean'>;
}
declare module 'canner-script/lib/models/date.js' {
  declare module.exports: $Exports<'canner-script/lib/models/date'>;
}
declare module 'canner-script/lib/models/file.js' {
  declare module.exports: $Exports<'canner-script/lib/models/file'>;
}
declare module 'canner-script/lib/models/geoPoint.js' {
  declare module.exports: $Exports<'canner-script/lib/models/geoPoint'>;
}
declare module 'canner-script/lib/models/image.js' {
  declare module.exports: $Exports<'canner-script/lib/models/image'>;
}
declare module 'canner-script/lib/models/index.js' {
  declare module.exports: $Exports<'canner-script/lib/models/index'>;
}
declare module 'canner-script/lib/models/mapPoint.js' {
  declare module.exports: $Exports<'canner-script/lib/models/mapPoint'>;
}
declare module 'canner-script/lib/models/number.js' {
  declare module.exports: $Exports<'canner-script/lib/models/number'>;
}
declare module 'canner-script/lib/models/object.js' {
  declare module.exports: $Exports<'canner-script/lib/models/object'>;
}
declare module 'canner-script/lib/models/relation.js' {
  declare module.exports: $Exports<'canner-script/lib/models/relation'>;
}
declare module 'canner-script/lib/models/root.js' {
  declare module.exports: $Exports<'canner-script/lib/models/root'>;
}
declare module 'canner-script/lib/models/string.js' {
  declare module.exports: $Exports<'canner-script/lib/models/string'>;
}
declare module 'canner-script/lib/utils.js' {
  declare module.exports: $Exports<'canner-script/lib/utils'>;
}
declare module 'canner-script/lib/validator.js' {
  declare module.exports: $Exports<'canner-script/lib/validator'>;
}
declare module 'canner-script/lib/visitorManager.js' {
  declare module.exports: $Exports<'canner-script/lib/visitorManager'>;
}
declare module 'canner-script/lib/visitors/body.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/body'>;
}
declare module 'canner-script/lib/visitors/fieldset.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/fieldset'>;
}
declare module 'canner-script/lib/visitors/hocs.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/hocs'>;
}
declare module 'canner-script/lib/visitors/index.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/index'>;
}
declare module 'canner-script/lib/visitors/layer1-2Fieldset.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/layer1-2Fieldset'>;
}
declare module 'canner-script/lib/visitors/layer3Fieldset.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/layer3Fieldset'>;
}
declare module 'canner-script/lib/visitors/layerGTE4Fieldset.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/layerGTE4Fieldset'>;
}
declare module 'canner-script/lib/visitors/validator.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/validator'>;
}
declare module 'canner-script/lib/visitors/variants.js' {
  declare module.exports: $Exports<'canner-script/lib/visitors/variants'>;
}
