// flow-typed signature: 1cb1008af80edf5f36bab890d4f8c6f9
// flow-typed version: <<STUB>>/canner-helpers_v1.0.0-beta.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-helpers/lib/cancelButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/confirmButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/context' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/createEmptyData' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/index' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/item' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/liteCMS' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/renderField' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-helpers/lib/cancelButton.js' {
  declare module.exports: $Exports<'canner-helpers/lib/cancelButton'>;
}
declare module 'canner-helpers/lib/confirmButton.js' {
  declare module.exports: $Exports<'canner-helpers/lib/confirmButton'>;
}
declare module 'canner-helpers/lib/context.js' {
  declare module.exports: $Exports<'canner-helpers/lib/context'>;
}
declare module 'canner-helpers/lib/createEmptyData.js' {
  declare module.exports: $Exports<'canner-helpers/lib/createEmptyData'>;
}
declare module 'canner-helpers/lib/index.js' {
  declare module.exports: $Exports<'canner-helpers/lib/index'>;
}
declare module 'canner-helpers/lib/item.js' {
  declare module.exports: $Exports<'canner-helpers/lib/item'>;
}
declare module 'canner-helpers/lib/liteCMS.js' {
  declare module.exports: $Exports<'canner-helpers/lib/liteCMS'>;
}
declare module 'canner-helpers/lib/renderField.js' {
  declare module.exports: $Exports<'canner-helpers/lib/renderField'>;
}
