// flow-typed signature: 5fe32c4402d2cbe848678a07bca8ef27
// flow-typed version: <<STUB>>/canner-schema-loader_v^1.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-schema-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-schema-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-schema-loader/lib/componentList' {
  declare module.exports: any;
}

declare module 'canner-schema-loader/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-schema-loader/lib/componentList.js' {
  declare module.exports: $Exports<'canner-schema-loader/lib/componentList'>;
}
declare module 'canner-schema-loader/lib/index.js' {
  declare module.exports: $Exports<'canner-schema-loader/lib/index'>;
}
