// flow-typed signature: cc389aa43978b2cc9e4d9d6f98c97c01
// flow-typed version: <<STUB>>/canner-layouts_v*/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-layouts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-layouts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-layouts/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'canner-layouts/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'canner-layouts/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Block' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Body' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Col' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Collapse' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Condition' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Default' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Focus' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/index' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/InnerBlock' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Row' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Tabs' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Block' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Body' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Col' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Collapse' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Condition' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Default' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Focus' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/index' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/InnerBlock' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Row' {
  declare module.exports: any;
}

declare module 'canner-layouts/src/Tabs' {
  declare module.exports: any;
}

declare module 'canner-layouts/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-layouts/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'canner-layouts/coverage/lcov-report/block-navigation'>;
}
declare module 'canner-layouts/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'canner-layouts/coverage/lcov-report/prettify'>;
}
declare module 'canner-layouts/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'canner-layouts/coverage/lcov-report/sorter'>;
}
declare module 'canner-layouts/lib/Block.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Block'>;
}
declare module 'canner-layouts/lib/Body.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Body'>;
}
declare module 'canner-layouts/lib/Col.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Col'>;
}
declare module 'canner-layouts/lib/Collapse.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Collapse'>;
}
declare module 'canner-layouts/lib/Condition.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Condition'>;
}
declare module 'canner-layouts/lib/Default.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Default'>;
}
declare module 'canner-layouts/lib/Focus.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Focus'>;
}
declare module 'canner-layouts/lib/index.js' {
  declare module.exports: $Exports<'canner-layouts/lib/index'>;
}
declare module 'canner-layouts/lib/InnerBlock.js' {
  declare module.exports: $Exports<'canner-layouts/lib/InnerBlock'>;
}
declare module 'canner-layouts/lib/Row.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Row'>;
}
declare module 'canner-layouts/lib/Tabs.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Tabs'>;
}
declare module 'canner-layouts/src/Block.js' {
  declare module.exports: $Exports<'canner-layouts/src/Block'>;
}
declare module 'canner-layouts/src/Body.js' {
  declare module.exports: $Exports<'canner-layouts/src/Body'>;
}
declare module 'canner-layouts/src/Col.js' {
  declare module.exports: $Exports<'canner-layouts/src/Col'>;
}
declare module 'canner-layouts/src/Collapse.js' {
  declare module.exports: $Exports<'canner-layouts/src/Collapse'>;
}
declare module 'canner-layouts/src/Condition.js' {
  declare module.exports: $Exports<'canner-layouts/src/Condition'>;
}
declare module 'canner-layouts/src/Default.js' {
  declare module.exports: $Exports<'canner-layouts/src/Default'>;
}
declare module 'canner-layouts/src/Focus.js' {
  declare module.exports: $Exports<'canner-layouts/src/Focus'>;
}
declare module 'canner-layouts/src/index.js' {
  declare module.exports: $Exports<'canner-layouts/src/index'>;
}
declare module 'canner-layouts/src/InnerBlock.js' {
  declare module.exports: $Exports<'canner-layouts/src/InnerBlock'>;
}
declare module 'canner-layouts/src/Row.js' {
  declare module.exports: $Exports<'canner-layouts/src/Row'>;
}
declare module 'canner-layouts/src/Tabs.js' {
  declare module.exports: $Exports<'canner-layouts/src/Tabs'>;
}
declare module 'canner-layouts/test/index.test.js' {
  declare module.exports: $Exports<'canner-layouts/test/index.test'>;
}
