// flow-typed signature: 115b40fb8bf777cc277a8c90b22641f9
// flow-typed version: <<STUB>>/canner-layouts_v1.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-layouts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-layouts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-layouts/lib/Block' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Body' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Collapse' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Default' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Focus' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/index' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/InnerBlock' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Row' {
  declare module.exports: any;
}

declare module 'canner-layouts/lib/Tabs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-layouts/lib/Block.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Block'>;
}
declare module 'canner-layouts/lib/Body.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Body'>;
}
declare module 'canner-layouts/lib/Collapse.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Collapse'>;
}
declare module 'canner-layouts/lib/Default.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Default'>;
}
declare module 'canner-layouts/lib/Focus.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Focus'>;
}
declare module 'canner-layouts/lib/index.js' {
  declare module.exports: $Exports<'canner-layouts/lib/index'>;
}
declare module 'canner-layouts/lib/InnerBlock.js' {
  declare module.exports: $Exports<'canner-layouts/lib/InnerBlock'>;
}
declare module 'canner-layouts/lib/Row.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Row'>;
}
declare module 'canner-layouts/lib/Tabs.js' {
  declare module.exports: $Exports<'canner-layouts/lib/Tabs'>;
}
