// flow-typed signature: a9c7b9cc8c75046a390d77da8922ef88
// flow-typed version: <<STUB>>/canner-ref-id_v0.1.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-ref-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-ref-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-ref-id/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-ref-id/lib/index.js' {
  declare module.exports: $Exports<'canner-ref-id/lib/index'>;
}
