// flow-typed signature: 2f3c0db2468182b30bccac933d3ff095
// flow-typed version: <<STUB>>/canner-compiler_v*/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-compiler/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'canner-compiler/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'canner-compiler/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/canner-node' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/index' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/parser' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/traverser' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/tree' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/types' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/visitor' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/canner-node' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/index' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/parser' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/traverser' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/tree' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/types' {
  declare module.exports: any;
}

declare module 'canner-compiler/src/visitor' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/node.test' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/parse.test' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/qa-compiler.test' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/traverse.test' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/tree.test' {
  declare module.exports: any;
}

declare module 'canner-compiler/test/visitor.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-compiler/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'canner-compiler/coverage/lcov-report/block-navigation'>;
}
declare module 'canner-compiler/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'canner-compiler/coverage/lcov-report/prettify'>;
}
declare module 'canner-compiler/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'canner-compiler/coverage/lcov-report/sorter'>;
}
declare module 'canner-compiler/lib/canner-node.js' {
  declare module.exports: $Exports<'canner-compiler/lib/canner-node'>;
}
declare module 'canner-compiler/lib/index.js' {
  declare module.exports: $Exports<'canner-compiler/lib/index'>;
}
declare module 'canner-compiler/lib/parser.js' {
  declare module.exports: $Exports<'canner-compiler/lib/parser'>;
}
declare module 'canner-compiler/lib/traverser.js' {
  declare module.exports: $Exports<'canner-compiler/lib/traverser'>;
}
declare module 'canner-compiler/lib/tree.js' {
  declare module.exports: $Exports<'canner-compiler/lib/tree'>;
}
declare module 'canner-compiler/lib/types.js' {
  declare module.exports: $Exports<'canner-compiler/lib/types'>;
}
declare module 'canner-compiler/lib/visitor.js' {
  declare module.exports: $Exports<'canner-compiler/lib/visitor'>;
}
declare module 'canner-compiler/src/canner-node.js' {
  declare module.exports: $Exports<'canner-compiler/src/canner-node'>;
}
declare module 'canner-compiler/src/index.js' {
  declare module.exports: $Exports<'canner-compiler/src/index'>;
}
declare module 'canner-compiler/src/parser.js' {
  declare module.exports: $Exports<'canner-compiler/src/parser'>;
}
declare module 'canner-compiler/src/traverser.js' {
  declare module.exports: $Exports<'canner-compiler/src/traverser'>;
}
declare module 'canner-compiler/src/tree.js' {
  declare module.exports: $Exports<'canner-compiler/src/tree'>;
}
declare module 'canner-compiler/src/types.js' {
  declare module.exports: $Exports<'canner-compiler/src/types'>;
}
declare module 'canner-compiler/src/visitor.js' {
  declare module.exports: $Exports<'canner-compiler/src/visitor'>;
}
declare module 'canner-compiler/test/node.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/node.test'>;
}
declare module 'canner-compiler/test/parse.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/parse.test'>;
}
declare module 'canner-compiler/test/qa-compiler.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/qa-compiler.test'>;
}
declare module 'canner-compiler/test/traverse.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/traverse.test'>;
}
declare module 'canner-compiler/test/tree.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/tree.test'>;
}
declare module 'canner-compiler/test/visitor.test.js' {
  declare module.exports: $Exports<'canner-compiler/test/visitor.test'>;
}
