// flow-typed signature: cc8ef2cd625ea362f15392718f1fe0a0
// flow-typed version: <<STUB>>/canner-graphql-interface_v^2.0.51/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-graphql-interface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-graphql-interface' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-graphql-interface/lib/config' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/cannerPlatformConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/dataLoaderConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/firebaseConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/firestoreAdminConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/firestoreConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/localStorageConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/memoryConnector' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/connector/types' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/graphqlClient/graphqlClient' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/graphqlClient/prismaClient' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/graphqlClient/types' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/index' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/link' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/resolver' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/types' {
  declare module.exports: any;
}

declare module 'canner-graphql-interface/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-graphql-interface/lib/config.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/config'>;
}
declare module 'canner-graphql-interface/lib/connector/cannerPlatformConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/cannerPlatformConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/dataLoaderConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/dataLoaderConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/firebaseConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/firebaseConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/firestoreAdminConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/firestoreAdminConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/firestoreConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/firestoreConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/localStorageConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/localStorageConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/memoryConnector.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/memoryConnector'>;
}
declare module 'canner-graphql-interface/lib/connector/types.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/connector/types'>;
}
declare module 'canner-graphql-interface/lib/graphqlClient/graphqlClient.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/graphqlClient/graphqlClient'>;
}
declare module 'canner-graphql-interface/lib/graphqlClient/prismaClient.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/graphqlClient/prismaClient'>;
}
declare module 'canner-graphql-interface/lib/graphqlClient/types.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/graphqlClient/types'>;
}
declare module 'canner-graphql-interface/lib/index.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/index'>;
}
declare module 'canner-graphql-interface/lib/link.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/link'>;
}
declare module 'canner-graphql-interface/lib/resolver.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/resolver'>;
}
declare module 'canner-graphql-interface/lib/types.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/types'>;
}
declare module 'canner-graphql-interface/lib/utils.js' {
  declare module.exports: $Exports<'canner-graphql-interface/lib/utils'>;
}
