// flow-typed signature: ec8619a306f9983da88885bc3812bf96
// flow-typed version: <<STUB>>/canner-helpers_v*/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-helpers/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'canner-helpers/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'canner-helpers/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/cancelButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/confirmButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/context' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/createEmptyData' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/createFakeData' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/index' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/item' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/liteCMS' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/types' {
  declare module.exports: any;
}

declare module 'canner-helpers/lib/utils' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/cancelButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/confirmButton' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/context' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/createEmptyData' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/createFakeData' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/index' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/item' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/liteCMS' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/types' {
  declare module.exports: any;
}

declare module 'canner-helpers/src/utils' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/cancelbutton.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/canner-react-cms-helpers.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/confirmbutton.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/createEmptyData.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/createFakeData.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/item.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/liteCMS.test' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/react163Adapter' {
  declare module.exports: any;
}

declare module 'canner-helpers/test/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-helpers/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'canner-helpers/coverage/lcov-report/block-navigation'>;
}
declare module 'canner-helpers/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'canner-helpers/coverage/lcov-report/prettify'>;
}
declare module 'canner-helpers/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'canner-helpers/coverage/lcov-report/sorter'>;
}
declare module 'canner-helpers/lib/cancelButton.js' {
  declare module.exports: $Exports<'canner-helpers/lib/cancelButton'>;
}
declare module 'canner-helpers/lib/confirmButton.js' {
  declare module.exports: $Exports<'canner-helpers/lib/confirmButton'>;
}
declare module 'canner-helpers/lib/context.js' {
  declare module.exports: $Exports<'canner-helpers/lib/context'>;
}
declare module 'canner-helpers/lib/createEmptyData.js' {
  declare module.exports: $Exports<'canner-helpers/lib/createEmptyData'>;
}
declare module 'canner-helpers/lib/createFakeData.js' {
  declare module.exports: $Exports<'canner-helpers/lib/createFakeData'>;
}
declare module 'canner-helpers/lib/index.js' {
  declare module.exports: $Exports<'canner-helpers/lib/index'>;
}
declare module 'canner-helpers/lib/item.js' {
  declare module.exports: $Exports<'canner-helpers/lib/item'>;
}
declare module 'canner-helpers/lib/liteCMS.js' {
  declare module.exports: $Exports<'canner-helpers/lib/liteCMS'>;
}
declare module 'canner-helpers/lib/types.js' {
  declare module.exports: $Exports<'canner-helpers/lib/types'>;
}
declare module 'canner-helpers/lib/utils.js' {
  declare module.exports: $Exports<'canner-helpers/lib/utils'>;
}
declare module 'canner-helpers/src/cancelButton.js' {
  declare module.exports: $Exports<'canner-helpers/src/cancelButton'>;
}
declare module 'canner-helpers/src/confirmButton.js' {
  declare module.exports: $Exports<'canner-helpers/src/confirmButton'>;
}
declare module 'canner-helpers/src/context.js' {
  declare module.exports: $Exports<'canner-helpers/src/context'>;
}
declare module 'canner-helpers/src/createEmptyData.js' {
  declare module.exports: $Exports<'canner-helpers/src/createEmptyData'>;
}
declare module 'canner-helpers/src/createFakeData.js' {
  declare module.exports: $Exports<'canner-helpers/src/createFakeData'>;
}
declare module 'canner-helpers/src/index.js' {
  declare module.exports: $Exports<'canner-helpers/src/index'>;
}
declare module 'canner-helpers/src/item.js' {
  declare module.exports: $Exports<'canner-helpers/src/item'>;
}
declare module 'canner-helpers/src/liteCMS.js' {
  declare module.exports: $Exports<'canner-helpers/src/liteCMS'>;
}
declare module 'canner-helpers/src/types.js' {
  declare module.exports: $Exports<'canner-helpers/src/types'>;
}
declare module 'canner-helpers/src/utils.js' {
  declare module.exports: $Exports<'canner-helpers/src/utils'>;
}
declare module 'canner-helpers/test/cancelbutton.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/cancelbutton.test'>;
}
declare module 'canner-helpers/test/canner-react-cms-helpers.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/canner-react-cms-helpers.test'>;
}
declare module 'canner-helpers/test/confirmbutton.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/confirmbutton.test'>;
}
declare module 'canner-helpers/test/createEmptyData.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/createEmptyData.test'>;
}
declare module 'canner-helpers/test/createFakeData.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/createFakeData.test'>;
}
declare module 'canner-helpers/test/item.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/item.test'>;
}
declare module 'canner-helpers/test/liteCMS.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/liteCMS.test'>;
}
declare module 'canner-helpers/test/react163Adapter.js' {
  declare module.exports: $Exports<'canner-helpers/test/react163Adapter'>;
}
declare module 'canner-helpers/test/utils.test.js' {
  declare module.exports: $Exports<'canner-helpers/test/utils.test'>;
}
