// flow-typed signature: 94d73607c866742fc922476e5f5653cc
// flow-typed version: <<STUB>>/canner-antd-theme_v^1.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-antd-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-antd-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'canner-antd-theme/index' {
  declare module.exports: $Exports<'canner-antd-theme'>;
}
declare module 'canner-antd-theme/index.js' {
  declare module.exports: $Exports<'canner-antd-theme'>;
}
