// flow-typed signature: a014bd3925da2a77e4a8fa1469c762e6
// flow-typed version: <<STUB>>/canner-ref-id_v*/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-ref-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-ref-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-ref-id/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'canner-ref-id/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'canner-ref-id/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'canner-ref-id/lib/index' {
  declare module.exports: any;
}

declare module 'canner-ref-id/src/index' {
  declare module.exports: any;
}

declare module 'canner-ref-id/test/canner-ref-id.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-ref-id/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'canner-ref-id/coverage/lcov-report/block-navigation'>;
}
declare module 'canner-ref-id/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'canner-ref-id/coverage/lcov-report/prettify'>;
}
declare module 'canner-ref-id/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'canner-ref-id/coverage/lcov-report/sorter'>;
}
declare module 'canner-ref-id/lib/index.js' {
  declare module.exports: $Exports<'canner-ref-id/lib/index'>;
}
declare module 'canner-ref-id/src/index.js' {
  declare module.exports: $Exports<'canner-ref-id/src/index'>;
}
declare module 'canner-ref-id/test/canner-ref-id.test.js' {
  declare module.exports: $Exports<'canner-ref-id/test/canner-ref-id.test'>;
}
