// flow-typed signature: 2f1114286f23c17b094944a6ad3341f8
// flow-typed version: <<STUB>>/canner-compiler_v^0.1.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canner-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canner-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canner-compiler/lib/canner-node' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/index' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/parser' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/traverser' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/tree' {
  declare module.exports: any;
}

declare module 'canner-compiler/lib/visitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canner-compiler/lib/canner-node.js' {
  declare module.exports: $Exports<'canner-compiler/lib/canner-node'>;
}
declare module 'canner-compiler/lib/index.js' {
  declare module.exports: $Exports<'canner-compiler/lib/index'>;
}
declare module 'canner-compiler/lib/parser.js' {
  declare module.exports: $Exports<'canner-compiler/lib/parser'>;
}
declare module 'canner-compiler/lib/traverser.js' {
  declare module.exports: $Exports<'canner-compiler/lib/traverser'>;
}
declare module 'canner-compiler/lib/tree.js' {
  declare module.exports: $Exports<'canner-compiler/lib/tree'>;
}
declare module 'canner-compiler/lib/visitor.js' {
  declare module.exports: $Exports<'canner-compiler/lib/visitor'>;
}
