// flow-typed signature: 84493280c3bdadcdef50b914ee80c6ec
// flow-typed version: <<STUB>>/enzyme-adapter-react-16.3_v^1.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-16.3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-adapter-react-16.3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-adapter-react-16.3/build/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16.3/build/ReactSixteenThreeAdapter' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16.3/src/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-adapter-react-16.3/build/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16.3/build/index'>;
}
declare module 'enzyme-adapter-react-16.3/build/ReactSixteenThreeAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16.3/build/ReactSixteenThreeAdapter'>;
}
declare module 'enzyme-adapter-react-16.3/src/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16.3/src/index'>;
}
declare module 'enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16.3/src/ReactSixteenThreeAdapter'>;
}
