// flow-typed signature: bc0bba1b9ff05cbe3a49a8c1750f0867
// flow-typed version: <<STUB>>/enzyme-to-json_v^3.3.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-to-json/createSerializer' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/mount' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/render' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/serializer' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/shallow' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-to-json/createSerializer.js' {
  declare module.exports: $Exports<'enzyme-to-json/createSerializer'>;
}
declare module 'enzyme-to-json/index' {
  declare module.exports: $Exports<'enzyme-to-json'>;
}
declare module 'enzyme-to-json/index.js' {
  declare module.exports: $Exports<'enzyme-to-json'>;
}
declare module 'enzyme-to-json/mount.js' {
  declare module.exports: $Exports<'enzyme-to-json/mount'>;
}
declare module 'enzyme-to-json/render.js' {
  declare module.exports: $Exports<'enzyme-to-json/render'>;
}
declare module 'enzyme-to-json/serializer.js' {
  declare module.exports: $Exports<'enzyme-to-json/serializer'>;
}
declare module 'enzyme-to-json/shallow.js' {
  declare module.exports: $Exports<'enzyme-to-json/shallow'>;
}
declare module 'enzyme-to-json/utils.js' {
  declare module.exports: $Exports<'enzyme-to-json/utils'>;
}
