// flow-typed signature: 878f9d3eed9b1c9455ef25072641c88e
// flow-typed version: <<STUB>>/eslint-config-google_v^0.9.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-google'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-google' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-google/index' {
  declare module.exports: $Exports<'eslint-config-google'>;
}
declare module 'eslint-config-google/index.js' {
  declare module.exports: $Exports<'eslint-config-google'>;
}
