// flow-typed signature: c6321c5bb658f96f737384a959b9e006
// flow-typed version: <<STUB>>/flat_v^4.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flat/cli' {
  declare module.exports: any;
}

declare module 'flat/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flat/cli.js' {
  declare module.exports: $Exports<'flat/cli'>;
}
declare module 'flat/index' {
  declare module.exports: $Exports<'flat'>;
}
declare module 'flat/index.js' {
  declare module.exports: $Exports<'flat'>;
}
declare module 'flat/test/test.js' {
  declare module.exports: $Exports<'flat/test/test'>;
}
