// flow-typed signature: 16dce49a558d6dcdf93452520bc1929f
// flow-typed version: <<STUB>>/gulp-typescript_v^5.0.0-alpha.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-typescript/release/compiler' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/host' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/input' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/main' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/output' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/project' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/reporter' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/types' {
  declare module.exports: any;
}

declare module 'gulp-typescript/release/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-typescript/release/compiler.js' {
  declare module.exports: $Exports<'gulp-typescript/release/compiler'>;
}
declare module 'gulp-typescript/release/host.js' {
  declare module.exports: $Exports<'gulp-typescript/release/host'>;
}
declare module 'gulp-typescript/release/input.js' {
  declare module.exports: $Exports<'gulp-typescript/release/input'>;
}
declare module 'gulp-typescript/release/main.js' {
  declare module.exports: $Exports<'gulp-typescript/release/main'>;
}
declare module 'gulp-typescript/release/output.js' {
  declare module.exports: $Exports<'gulp-typescript/release/output'>;
}
declare module 'gulp-typescript/release/project.js' {
  declare module.exports: $Exports<'gulp-typescript/release/project'>;
}
declare module 'gulp-typescript/release/reporter.js' {
  declare module.exports: $Exports<'gulp-typescript/release/reporter'>;
}
declare module 'gulp-typescript/release/types.js' {
  declare module.exports: $Exports<'gulp-typescript/release/types'>;
}
declare module 'gulp-typescript/release/utils.js' {
  declare module.exports: $Exports<'gulp-typescript/release/utils'>;
}
