// flow-typed signature: 41aa9c55b41c2dc34e1ce78ad1b4fe45
// flow-typed version: <<STUB>>/immer_v1.5.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immer/dist/immer' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.module' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immer/dist/immer.js' {
  declare module.exports: $Exports<'immer/dist/immer'>;
}
declare module 'immer/dist/immer.module.js' {
  declare module.exports: $Exports<'immer/dist/immer.module'>;
}
declare module 'immer/dist/immer.umd.js' {
  declare module.exports: $Exports<'immer/dist/immer.umd'>;
}
