// flow-typed signature: 3baec7da49b44f3cbd291647c0821527
// flow-typed version: <<STUB>>/lowdb_v^1.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lowdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lowdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lowdb/adapters/_stringify' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/Base' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/FileAsync' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/FileSync' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/LocalStorage' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/Memory' {
  declare module.exports: any;
}

declare module 'lowdb/dist/LocalStorage' {
  declare module.exports: any;
}

declare module 'lowdb/dist/LocalStorage.min' {
  declare module.exports: any;
}

declare module 'lowdb/dist/low' {
  declare module.exports: any;
}

declare module 'lowdb/dist/low.min' {
  declare module.exports: any;
}

declare module 'lowdb/lib/common' {
  declare module.exports: any;
}

declare module 'lowdb/lib/fp' {
  declare module.exports: any;
}

declare module 'lowdb/lib/main' {
  declare module.exports: any;
}

declare module 'lowdb/lib/nano' {
  declare module.exports: any;
}

declare module 'lowdb/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lowdb/adapters/_stringify.js' {
  declare module.exports: $Exports<'lowdb/adapters/_stringify'>;
}
declare module 'lowdb/adapters/Base.js' {
  declare module.exports: $Exports<'lowdb/adapters/Base'>;
}
declare module 'lowdb/adapters/FileAsync.js' {
  declare module.exports: $Exports<'lowdb/adapters/FileAsync'>;
}
declare module 'lowdb/adapters/FileSync.js' {
  declare module.exports: $Exports<'lowdb/adapters/FileSync'>;
}
declare module 'lowdb/adapters/LocalStorage.js' {
  declare module.exports: $Exports<'lowdb/adapters/LocalStorage'>;
}
declare module 'lowdb/adapters/Memory.js' {
  declare module.exports: $Exports<'lowdb/adapters/Memory'>;
}
declare module 'lowdb/dist/LocalStorage.js' {
  declare module.exports: $Exports<'lowdb/dist/LocalStorage'>;
}
declare module 'lowdb/dist/LocalStorage.min.js' {
  declare module.exports: $Exports<'lowdb/dist/LocalStorage.min'>;
}
declare module 'lowdb/dist/low.js' {
  declare module.exports: $Exports<'lowdb/dist/low'>;
}
declare module 'lowdb/dist/low.min.js' {
  declare module.exports: $Exports<'lowdb/dist/low.min'>;
}
declare module 'lowdb/lib/common.js' {
  declare module.exports: $Exports<'lowdb/lib/common'>;
}
declare module 'lowdb/lib/fp.js' {
  declare module.exports: $Exports<'lowdb/lib/fp'>;
}
declare module 'lowdb/lib/main.js' {
  declare module.exports: $Exports<'lowdb/lib/main'>;
}
declare module 'lowdb/lib/nano.js' {
  declare module.exports: $Exports<'lowdb/lib/nano'>;
}
declare module 'lowdb/webpack.config.js' {
  declare module.exports: $Exports<'lowdb/webpack.config'>;
}
