// flow-typed signature: c356d52846e670d30856163bd1f2b0c9
// flow-typed version: <<STUB>>/object-path_v^0.11.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-path/benchmark' {
  declare module.exports: any;
}

declare module 'object-path/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-path/benchmark.js' {
  declare module.exports: $Exports<'object-path/benchmark'>;
}
declare module 'object-path/index' {
  declare module.exports: $Exports<'object-path'>;
}
declare module 'object-path/index.js' {
  declare module.exports: $Exports<'object-path'>;
}
declare module 'object-path/test.js' {
  declare module.exports: $Exports<'object-path/test'>;
}
