// flow-typed signature: f46f28395617213e83efe7e78e5206f6
// flow-typed version: <<STUB>>/pluralize_v7.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pluralize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pluralize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pluralize/pluralize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pluralize/pluralize.js' {
  declare module.exports: $Exports<'pluralize/pluralize'>;
}
