// flow-typed signature: 09833a19a4f5202c8af927fd8834f390
// flow-typed version: <<STUB>>/promise-polyfill_v^7.1.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-polyfill/dist/polyfill' {
  declare module.exports: any;
}

declare module 'promise-polyfill/dist/polyfill.min' {
  declare module.exports: any;
}

declare module 'promise-polyfill/dist/promise' {
  declare module.exports: any;
}

declare module 'promise-polyfill/dist/promise.min' {
  declare module.exports: any;
}

declare module 'promise-polyfill/lib/index' {
  declare module.exports: any;
}

declare module 'promise-polyfill/lib/polyfill' {
  declare module.exports: any;
}

declare module 'promise-polyfill/src/index' {
  declare module.exports: any;
}

declare module 'promise-polyfill/src/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-polyfill/dist/polyfill.js' {
  declare module.exports: $Exports<'promise-polyfill/dist/polyfill'>;
}
declare module 'promise-polyfill/dist/polyfill.min.js' {
  declare module.exports: $Exports<'promise-polyfill/dist/polyfill.min'>;
}
declare module 'promise-polyfill/dist/promise.js' {
  declare module.exports: $Exports<'promise-polyfill/dist/promise'>;
}
declare module 'promise-polyfill/dist/promise.min.js' {
  declare module.exports: $Exports<'promise-polyfill/dist/promise.min'>;
}
declare module 'promise-polyfill/lib/index.js' {
  declare module.exports: $Exports<'promise-polyfill/lib/index'>;
}
declare module 'promise-polyfill/lib/polyfill.js' {
  declare module.exports: $Exports<'promise-polyfill/lib/polyfill'>;
}
declare module 'promise-polyfill/src/index.js' {
  declare module.exports: $Exports<'promise-polyfill/src/index'>;
}
declare module 'promise-polyfill/src/polyfill.js' {
  declare module.exports: $Exports<'promise-polyfill/src/polyfill'>;
}
