// flow-typed signature: e7b94f1e8336a9bece2ea691e8d41c72
// flow-typed version: <<STUB>>/react-spinners_v^0.2.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/blank_slate' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/helpers/index' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/index' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/docs/vendor' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/code' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/color_picker' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/form' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/index' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/components/loader_item' {
  declare module.exports: any;
}

declare module 'react-spinners/examples/index' {
  declare module.exports: any;
}

declare module 'react-spinners/src/helpers/index' {
  declare module.exports: any;
}

declare module 'react-spinners/src/index' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/src/spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/blank_slate.jsx' {
  declare module.exports: $Exports<'react-spinners/blank_slate'>;
}
declare module 'react-spinners/dist/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/dist/helpers/index'>;
}
declare module 'react-spinners/dist/index.js' {
  declare module.exports: $Exports<'react-spinners/dist/index'>;
}
declare module 'react-spinners/dist/spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/BarLoader'>;
}
declare module 'react-spinners/dist/spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/BeatLoader'>;
}
declare module 'react-spinners/dist/spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/BounceLoader'>;
}
declare module 'react-spinners/dist/spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/CircleLoader'>;
}
declare module 'react-spinners/dist/spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/dist/spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/ClipLoader'>;
}
declare module 'react-spinners/dist/spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/DotLoader'>;
}
declare module 'react-spinners/dist/spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/FadeLoader'>;
}
declare module 'react-spinners/dist/spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/GridLoader'>;
}
declare module 'react-spinners/dist/spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/HashLoader'>;
}
declare module 'react-spinners/dist/spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/MoonLoader'>;
}
declare module 'react-spinners/dist/spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/PacmanLoader'>;
}
declare module 'react-spinners/dist/spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/PropagateLoader'>;
}
declare module 'react-spinners/dist/spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/PulseLoader'>;
}
declare module 'react-spinners/dist/spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/RingLoader'>;
}
declare module 'react-spinners/dist/spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/RiseLoader'>;
}
declare module 'react-spinners/dist/spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/RotateLoader'>;
}
declare module 'react-spinners/dist/spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/ScaleLoader'>;
}
declare module 'react-spinners/dist/spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/SkewLoader'>;
}
declare module 'react-spinners/dist/spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/SquareLoader'>;
}
declare module 'react-spinners/dist/spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/dist/spinners/SyncLoader'>;
}
declare module 'react-spinners/docs/bundle.js' {
  declare module.exports: $Exports<'react-spinners/docs/bundle'>;
}
declare module 'react-spinners/docs/vendor.js' {
  declare module.exports: $Exports<'react-spinners/docs/vendor'>;
}
declare module 'react-spinners/examples/components/code.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/code'>;
}
declare module 'react-spinners/examples/components/color_picker.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/color_picker'>;
}
declare module 'react-spinners/examples/components/form.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/form'>;
}
declare module 'react-spinners/examples/components/index.js' {
  declare module.exports: $Exports<'react-spinners/examples/components/index'>;
}
declare module 'react-spinners/examples/components/loader_item.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/components/loader_item'>;
}
declare module 'react-spinners/examples/index.jsx' {
  declare module.exports: $Exports<'react-spinners/examples/index'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/src/helpers/index.js' {
  declare module.exports: $Exports<'react-spinners/src/helpers/index'>;
}
declare module 'react-spinners/src/index.js' {
  declare module.exports: $Exports<'react-spinners/src/index'>;
}
declare module 'react-spinners/src/spinners/BarLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/BarLoader'>;
}
declare module 'react-spinners/src/spinners/BeatLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/BeatLoader'>;
}
declare module 'react-spinners/src/spinners/BounceLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/BounceLoader'>;
}
declare module 'react-spinners/src/spinners/CircleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/CircleLoader'>;
}
declare module 'react-spinners/src/spinners/ClimbingBoxLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/src/spinners/ClipLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/ClipLoader'>;
}
declare module 'react-spinners/src/spinners/DotLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/DotLoader'>;
}
declare module 'react-spinners/src/spinners/FadeLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/FadeLoader'>;
}
declare module 'react-spinners/src/spinners/GridLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/GridLoader'>;
}
declare module 'react-spinners/src/spinners/HashLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/HashLoader'>;
}
declare module 'react-spinners/src/spinners/MoonLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/MoonLoader'>;
}
declare module 'react-spinners/src/spinners/PacmanLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/PacmanLoader'>;
}
declare module 'react-spinners/src/spinners/PropagateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/PropagateLoader'>;
}
declare module 'react-spinners/src/spinners/PulseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/PulseLoader'>;
}
declare module 'react-spinners/src/spinners/RingLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/RingLoader'>;
}
declare module 'react-spinners/src/spinners/RiseLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/RiseLoader'>;
}
declare module 'react-spinners/src/spinners/RotateLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/RotateLoader'>;
}
declare module 'react-spinners/src/spinners/ScaleLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/ScaleLoader'>;
}
declare module 'react-spinners/src/spinners/SkewLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/SkewLoader'>;
}
declare module 'react-spinners/src/spinners/SquareLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/SquareLoader'>;
}
declare module 'react-spinners/src/spinners/SyncLoader.jsx' {
  declare module.exports: $Exports<'react-spinners/src/spinners/SyncLoader'>;
}
declare module 'react-spinners/webpack.config.js' {
  declare module.exports: $Exports<'react-spinners/webpack.config'>;
}
