// flow-typed signature: 9f153bc5f83591252b5343a320cc3707
// flow-typed version: <<STUB>>/react-content-loader_v^3.1.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-content-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-content-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-content-loader/dist/react-content-loader.cjs' {
  declare module.exports: any;
}

declare module 'react-content-loader/dist/react-content-loader.es' {
  declare module.exports: any;
}

declare module 'react-content-loader/dist/react-content-loader' {
  declare module.exports: any;
}

declare module 'react-content-loader/dist/react-content-loader.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-content-loader/dist/react-content-loader.cjs.js' {
  declare module.exports: $Exports<'react-content-loader/dist/react-content-loader.cjs'>;
}
declare module 'react-content-loader/dist/react-content-loader.es.js' {
  declare module.exports: $Exports<'react-content-loader/dist/react-content-loader.es'>;
}
declare module 'react-content-loader/dist/react-content-loader.js' {
  declare module.exports: $Exports<'react-content-loader/dist/react-content-loader'>;
}
declare module 'react-content-loader/dist/react-content-loader.min.js' {
  declare module.exports: $Exports<'react-content-loader/dist/react-content-loader.min'>;
}
