// flow-typed signature: 62dfd519763144f85b4ec7b3c6e2b76b
// flow-typed version: <<STUB>>/react-vega_v^4.0.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-vega'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-vega' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-vega/dist/react-vega.min' {
  declare module.exports: any;
}

declare module 'react-vega/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-vega/dist/react-vega.min.js' {
  declare module.exports: $Exports<'react-vega/dist/react-vega.min'>;
}
declare module 'react-vega/src/index.js' {
  declare module.exports: $Exports<'react-vega/src/index'>;
}
