// flow-typed signature: 30145d9c71561673bcad4a2384bf1ee2
// flow-typed version: <<STUB>>/ts-jest_v^23.10.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-jest/cli' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/config/init' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/config/migrate' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/help' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/helpers/presets' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/cli/index' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/compiler' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/config-set' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/create-jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/jest-config-resolver' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/config/paths-to-module-name-mapper' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/index' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/transformers/hoist-jest' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/transformers/index' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/ts-jest-transformer' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/types' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/backports' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/exported' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/get-package-version' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/hacks' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/importer' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/json' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/jsonable-value' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/logger' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/memoize' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/messages' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/normalize-slashes' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/sha1' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/testing' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/ts-error' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/util/version-checkers' {
  declare module.exports: any;
}

declare module 'ts-jest/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/preprocessor' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/create' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/default/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/index' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-babel/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/presets/js-with-ts/jest-preset' {
  declare module.exports: any;
}

declare module 'ts-jest/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-jest/cli.js' {
  declare module.exports: $Exports<'ts-jest/cli'>;
}
declare module 'ts-jest/dist/cli/config/init.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/config/init'>;
}
declare module 'ts-jest/dist/cli/config/migrate.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/config/migrate'>;
}
declare module 'ts-jest/dist/cli/help.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/help'>;
}
declare module 'ts-jest/dist/cli/helpers/presets.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/helpers/presets'>;
}
declare module 'ts-jest/dist/cli/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/cli/index'>;
}
declare module 'ts-jest/dist/compiler.js' {
  declare module.exports: $Exports<'ts-jest/dist/compiler'>;
}
declare module 'ts-jest/dist/config/config-set.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/config-set'>;
}
declare module 'ts-jest/dist/config/create-jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/create-jest-preset'>;
}
declare module 'ts-jest/dist/config/jest-config-resolver.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/jest-config-resolver'>;
}
declare module 'ts-jest/dist/config/paths-to-module-name-mapper.js' {
  declare module.exports: $Exports<'ts-jest/dist/config/paths-to-module-name-mapper'>;
}
declare module 'ts-jest/dist/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/index'>;
}
declare module 'ts-jest/dist/transformers/hoist-jest.js' {
  declare module.exports: $Exports<'ts-jest/dist/transformers/hoist-jest'>;
}
declare module 'ts-jest/dist/transformers/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/transformers/index'>;
}
declare module 'ts-jest/dist/ts-jest-transformer.js' {
  declare module.exports: $Exports<'ts-jest/dist/ts-jest-transformer'>;
}
declare module 'ts-jest/dist/types.js' {
  declare module.exports: $Exports<'ts-jest/dist/types'>;
}
declare module 'ts-jest/dist/util/backports.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/backports'>;
}
declare module 'ts-jest/dist/util/exported.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/exported'>;
}
declare module 'ts-jest/dist/util/get-package-version.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/get-package-version'>;
}
declare module 'ts-jest/dist/util/hacks.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/hacks'>;
}
declare module 'ts-jest/dist/util/importer.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/importer'>;
}
declare module 'ts-jest/dist/util/json.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/json'>;
}
declare module 'ts-jest/dist/util/jsonable-value.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/jsonable-value'>;
}
declare module 'ts-jest/dist/util/logger.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/logger'>;
}
declare module 'ts-jest/dist/util/memoize.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/memoize'>;
}
declare module 'ts-jest/dist/util/messages.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/messages'>;
}
declare module 'ts-jest/dist/util/normalize-slashes.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/normalize-slashes'>;
}
declare module 'ts-jest/dist/util/sha1.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/sha1'>;
}
declare module 'ts-jest/dist/util/testing.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/testing'>;
}
declare module 'ts-jest/dist/util/ts-error.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/ts-error'>;
}
declare module 'ts-jest/dist/util/version-checkers.js' {
  declare module.exports: $Exports<'ts-jest/dist/util/version-checkers'>;
}
declare module 'ts-jest/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/jest-preset'>;
}
declare module 'ts-jest/preprocessor.js' {
  declare module.exports: $Exports<'ts-jest/preprocessor'>;
}
declare module 'ts-jest/presets/create.js' {
  declare module.exports: $Exports<'ts-jest/presets/create'>;
}
declare module 'ts-jest/presets/default/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/default/jest-preset'>;
}
declare module 'ts-jest/presets/index.js' {
  declare module.exports: $Exports<'ts-jest/presets/index'>;
}
declare module 'ts-jest/presets/js-with-babel/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-babel/jest-preset'>;
}
declare module 'ts-jest/presets/js-with-ts/jest-preset.js' {
  declare module.exports: $Exports<'ts-jest/presets/js-with-ts/jest-preset'>;
}
declare module 'ts-jest/utils/index.js' {
  declare module.exports: $Exports<'ts-jest/utils/index'>;
}
