// flow-typed signature: f82e82d56138f77ca4ace5bd9bbf8ac8
// flow-typed version: <<STUB>>/ts-loader_v^4.4.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-loader/dist/after-compile' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/compilerSetup' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/config' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/constants' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/index' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/instances' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/interfaces' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/logger' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/resolver' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/servicesHost' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/utils' {
  declare module.exports: any;
}

declare module 'ts-loader/dist/watch-run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-loader/dist/after-compile.js' {
  declare module.exports: $Exports<'ts-loader/dist/after-compile'>;
}
declare module 'ts-loader/dist/compilerSetup.js' {
  declare module.exports: $Exports<'ts-loader/dist/compilerSetup'>;
}
declare module 'ts-loader/dist/config.js' {
  declare module.exports: $Exports<'ts-loader/dist/config'>;
}
declare module 'ts-loader/dist/constants.js' {
  declare module.exports: $Exports<'ts-loader/dist/constants'>;
}
declare module 'ts-loader/dist/index.js' {
  declare module.exports: $Exports<'ts-loader/dist/index'>;
}
declare module 'ts-loader/dist/instances.js' {
  declare module.exports: $Exports<'ts-loader/dist/instances'>;
}
declare module 'ts-loader/dist/interfaces.js' {
  declare module.exports: $Exports<'ts-loader/dist/interfaces'>;
}
declare module 'ts-loader/dist/logger.js' {
  declare module.exports: $Exports<'ts-loader/dist/logger'>;
}
declare module 'ts-loader/dist/resolver.js' {
  declare module.exports: $Exports<'ts-loader/dist/resolver'>;
}
declare module 'ts-loader/dist/servicesHost.js' {
  declare module.exports: $Exports<'ts-loader/dist/servicesHost'>;
}
declare module 'ts-loader/dist/utils.js' {
  declare module.exports: $Exports<'ts-loader/dist/utils'>;
}
declare module 'ts-loader/dist/watch-run.js' {
  declare module.exports: $Exports<'ts-loader/dist/watch-run'>;
}
declare module 'ts-loader/index' {
  declare module.exports: $Exports<'ts-loader'>;
}
declare module 'ts-loader/index.js' {
  declare module.exports: $Exports<'ts-loader'>;
}
