// flow-typed signature: d865137af87785d5768f3bd9f8f0e5dc
// flow-typed version: <<STUB>>/vega-lib_v^4.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-lib/build/vega-core' {
  declare module.exports: any;
}

declare module 'vega-lib/build/vega-core.min' {
  declare module.exports: any;
}

declare module 'vega-lib/build/vega' {
  declare module.exports: any;
}

declare module 'vega-lib/build/vega.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-lib/build/vega-core.js' {
  declare module.exports: $Exports<'vega-lib/build/vega-core'>;
}
declare module 'vega-lib/build/vega-core.min.js' {
  declare module.exports: $Exports<'vega-lib/build/vega-core.min'>;
}
declare module 'vega-lib/build/vega.js' {
  declare module.exports: $Exports<'vega-lib/build/vega'>;
}
declare module 'vega-lib/build/vega.min.js' {
  declare module.exports: $Exports<'vega-lib/build/vega.min'>;
}
declare module 'vega-lib/index' {
  declare module.exports: $Exports<'vega-lib'>;
}
declare module 'vega-lib/index.js' {
  declare module.exports: $Exports<'vega-lib'>;
}
