// flow-typed signature: 52fdb101e1ef7c0287b4fa04938bfce1
// flow-typed version: <<STUB>>/vega-tooltip_v^0.13.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-tooltip/build/defaults' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/formatValue' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/Handler' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/index' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/position' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/style' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/vega-tooltip' {
  declare module.exports: any;
}

declare module 'vega-tooltip/build/vega-tooltip.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-tooltip/build/defaults.js' {
  declare module.exports: $Exports<'vega-tooltip/build/defaults'>;
}
declare module 'vega-tooltip/build/formatValue.js' {
  declare module.exports: $Exports<'vega-tooltip/build/formatValue'>;
}
declare module 'vega-tooltip/build/Handler.js' {
  declare module.exports: $Exports<'vega-tooltip/build/Handler'>;
}
declare module 'vega-tooltip/build/index.js' {
  declare module.exports: $Exports<'vega-tooltip/build/index'>;
}
declare module 'vega-tooltip/build/position.js' {
  declare module.exports: $Exports<'vega-tooltip/build/position'>;
}
declare module 'vega-tooltip/build/style.js' {
  declare module.exports: $Exports<'vega-tooltip/build/style'>;
}
declare module 'vega-tooltip/build/vega-tooltip.js' {
  declare module.exports: $Exports<'vega-tooltip/build/vega-tooltip'>;
}
declare module 'vega-tooltip/build/vega-tooltip.min.js' {
  declare module.exports: $Exports<'vega-tooltip/build/vega-tooltip.min'>;
}
