// flow-typed signature: e89383cee4d4c0f8a0fb5c65e5a718a2
// flow-typed version: <<STUB>>/victory_v^30.5.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victory/dist/victory' {
  declare module.exports: any;
}

declare module 'victory/dist/victory.min' {
  declare module.exports: any;
}

declare module 'victory/es/index' {
  declare module.exports: any;
}

declare module 'victory/lib/index' {
  declare module.exports: any;
}

declare module 'victory/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victory/dist/victory.js' {
  declare module.exports: $Exports<'victory/dist/victory'>;
}
declare module 'victory/dist/victory.min.js' {
  declare module.exports: $Exports<'victory/dist/victory.min'>;
}
declare module 'victory/es/index.js' {
  declare module.exports: $Exports<'victory/es/index'>;
}
declare module 'victory/lib/index.js' {
  declare module.exports: $Exports<'victory/lib/index'>;
}
declare module 'victory/src/index.js' {
  declare module.exports: $Exports<'victory/src/index'>;
}
