// flow-typed signature: 4b9169c31a6b8fc91e3d960bee2a04cb
// flow-typed version: <<STUB>>/@babel/plugin-proposal-logical-assignment-operators_v7.0.0-beta.54/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-logical-assignment-operators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-logical-assignment-operators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-logical-assignment-operators/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-logical-assignment-operators/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-logical-assignment-operators/lib/index'>;
}
