// flow-typed signature: 35cb64b28a1857faa4d12517865e22d2
// flow-typed version: <<STUB>>/@babel/plugin-proposal-export-namespace-from_v7.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-export-namespace-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-export-namespace-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-export-namespace-from/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-export-namespace-from/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-export-namespace-from/lib/index'>;
}
