// flow-typed signature: d1d3df1e6e61f923c657d925becc2cfb
// flow-typed version: <<STUB>>/@babel/plugin-syntax-import-meta_v7.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-import-meta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-import-meta' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-import-meta/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-import-meta/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-import-meta/lib/index'>;
}
