// flow-typed signature: c96fbe4f6f4daef6b8ae488b1f3fd526
// flow-typed version: <<STUB>>/@canner/antd-components_v^0.5.28/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/antd-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/antd-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/antd-components/lib/index' {
  declare module.exports: any;
}

declare module '@canner/antd-components/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/antd-components/lib/index.js' {
  declare module.exports: $Exports<'@canner/antd-components/lib/index'>;
}
declare module '@canner/antd-components/src/index.js' {
  declare module.exports: $Exports<'@canner/antd-components/src/index'>;
}
