// flow-typed signature: 3461f4dcf9b7b1b9a695461a72c93ce8
// flow-typed version: <<STUB>>/@canner/antd-locales_vlatest/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/antd-locales'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/antd-locales' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/antd-locales/lib/index' {
  declare module.exports: any;
}

declare module '@canner/antd-locales/lib/renderFunc' {
  declare module.exports: any;
}

declare module '@canner/antd-locales/src/index' {
  declare module.exports: any;
}

declare module '@canner/antd-locales/src/renderFunc' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/antd-locales/lib/index.js' {
  declare module.exports: $Exports<'@canner/antd-locales/lib/index'>;
}
declare module '@canner/antd-locales/lib/renderFunc.js' {
  declare module.exports: $Exports<'@canner/antd-locales/lib/renderFunc'>;
}
declare module '@canner/antd-locales/src/index.js' {
  declare module.exports: $Exports<'@canner/antd-locales/src/index'>;
}
declare module '@canner/antd-locales/src/renderFunc.js' {
  declare module.exports: $Exports<'@canner/antd-locales/src/renderFunc'>;
}
