// flow-typed signature: bb3d75e9e11e1d94dd8ace0585e6077b
// flow-typed version: <<STUB>>/@canner/antd-components_v^0.3.0-beta.8/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/antd-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/antd-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/antd-components/lib/index' {
  declare module.exports: any;
}

declare module '@canner/antd-components/lib/renderFunc' {
  declare module.exports: any;
}

declare module '@canner/antd-components/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/antd-components/lib/index.js' {
  declare module.exports: $Exports<'@canner/antd-components/lib/index'>;
}
declare module '@canner/antd-components/lib/renderFunc.js' {
  declare module.exports: $Exports<'@canner/antd-components/lib/renderFunc'>;
}
declare module '@canner/antd-components/src/index.js' {
  declare module.exports: $Exports<'@canner/antd-components/src/index'>;
}
