// flow-typed signature: 610e476f4acac60c554b88305ccf7dbd
// flow-typed version: <<STUB>>/@canner/cache_v*/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/cache/lib/index' {
  declare module.exports: any;
}

declare module '@canner/cache/lib/types' {
  declare module.exports: any;
}

declare module '@canner/cache/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/cache/lib/index.js' {
  declare module.exports: $Exports<'@canner/cache/lib/index'>;
}
declare module '@canner/cache/lib/types.js' {
  declare module.exports: $Exports<'@canner/cache/lib/types'>;
}
declare module '@canner/cache/test/index.test.js' {
  declare module.exports: $Exports<'@canner/cache/test/index.test'>;
}
