// flow-typed signature: b6d820ce48624ba3028db022b244171c
// flow-typed version: <<STUB>>/@canner/vega-charts_v^0.1.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/vega-charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/vega-charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/vega-charts/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/vega-charts/lib/index.js' {
  declare module.exports: $Exports<'@canner/vega-charts/lib/index'>;
}
