// flow-typed signature: 715673d3bffb6a6a8209f4724fd6c4ab
// flow-typed version: <<STUB>>/@canner/victory-bar-stack_v^0.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/victory-bar-stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/victory-bar-stack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/victory-bar-stack/lib/index' {
  declare module.exports: any;
}

declare module '@canner/victory-bar-stack/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/victory-bar-stack/lib/index.js' {
  declare module.exports: $Exports<'@canner/victory-bar-stack/lib/index'>;
}
declare module '@canner/victory-bar-stack/src/index.js' {
  declare module.exports: $Exports<'@canner/victory-bar-stack/src/index'>;
}
