// flow-typed signature: b24663d069e558b0701fa1044e16b920
// flow-typed version: <<STUB>>/@canner/victory-bar_v^0.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@canner/victory-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@canner/victory-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@canner/victory-bar/lib/index' {
  declare module.exports: any;
}

declare module '@canner/victory-bar/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@canner/victory-bar/lib/index.js' {
  declare module.exports: $Exports<'@canner/victory-bar/lib/index'>;
}
declare module '@canner/victory-bar/src/index.js' {
  declare module.exports: $Exports<'@canner/victory-bar/src/index'>;
}
